[project]
name = "finetunedllm"
version = "0.1.0"
description = "Fine tuning an llm to learn about embedded systems."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "docling>=2.44.0",
    "langflow>=1.5.0.post1",
    "litellm>=1.60.2",
]
